<a href="https://colab.research.google.com/github/yourmusician2-sudo/ai-powered-route-optimization-system-for-cold-chain-perishables/blob/main/EDA_AmazonPrimeVideo_QA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from matplotlib import ticker as mtick

In [2]:
df = pd.read_csv("/content/amazon_prime_users.csv")

In [3]:
df.head()

,User ID,Name,Email Address,Username,Date of Birth,Gender,Location,Membership Start Date,Membership End Date,Subscription Plan,Payment Information,Renewal Status,Usage Frequency,Purchase History,Favorite Genres,Devices Used,Engagement Metrics,Feedback/Ratings,Customer Support Interactions
0,1,Ronald Murphy,williamholland@example.com,williamholland,1953-06-03,Male,Rebeccachester,2024-01-15,2025-01-14,Annual,Mastercard,Manual,Regular,Electronics,Documentary,Smart TV,Medium,3.6,3
1,2,Scott Allen,scott22@example.org,scott22,1978-07-08,Male,Mcphersonview,2024-01-07,2025-01-06,Monthly,Visa,Manual,Regular,Electronics,Horror,Smartphone,Medium,3.8,7
2,3,Jonathan Parrish,brooke16@example.org,brooke16,1994-12-06,Female,Youngfort,2024-04-13,2025-04-13,Monthly,Mastercard,Manual,Regular,Books,Comedy,Smart TV,Low,3.3,8
3,4,Megan Williams,elizabeth31@example.net,elizabeth31,1964-12-22,Female,Feliciashire,2024-01-24,2025-01-23,Monthly,Amex,Auto-renew,Regular,Electronics,Documentary,Smart TV,High,3.3,7
4,5,Kathryn Brown,pattersonalexandra@example.org,pattersonalexandra,1961-06-04,Male,Port Deborah,2024-02-14,2025-02-13,Annual,Visa,Auto-renew,Frequent,Clothing,Drama,Smart TV,Low,4.3,1

In [4]:
df.shape

(2500, 19)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   User ID                        2500 non-null   int64
 1   Name                           2500 non-null   object
 2   Email Address                  2500 non-null   object
 3   Username                       2500 non-null   object
 4   Date of Birth                  2500 non-null   object
 5   Gender                         2500 non-null   object
 6   Location                       2500 non-null   object
 7   Membership Start Date          2500 non-null   object
 8   Membership End Date            2500 non-null   object
 9   Subscription Plan              2500 non-null   object
 10  Payment Information            2500 non-null   object
 11  Renewal Status                 2500 non-null   object
 12  Usage Frequency                2500 non-null   object
 13  Purchase History               2500 non-null   object
 14  Favorite Genres                2500 non-null   object
 15  Devices Used                   2500 non-null   object
 16  Engagement Metrics             2500 non-null   object
 17  Feedback/Ratings               2500 non-null   float64
 18  Customer Support Interactions  2500 non-null   int64
dtypes: float64(1), int64(2), object(16)
memory usage: 371.2+ KB

In [6]:
df.describe()

          User ID  Feedback/Ratings  Customer Support Interactions
count  2500.00000       2500.000000                    2500.000000
mean   1250.50000          4.004760                       4.951600
std     721.83216          0.580769                       3.191572
min       1.00000          3.000000                       0.000000
25%     625.75000          3.500000                       2.000000
50%    1250.50000          4.000000                       5.000000
75%    1875.25000          4.500000                       8.000000
max    2500.00000          5.000000                      10.000000

In [7]:
df.columns.values

array(['User ID', 'Name', 'Email Address', 'Username', 'Date of Birth',
       'Gender', 'Location', 'Membership Start Date',
       'Membership End Date', 'Subscription Plan', 'Payment Information',
       'Renewal Status', 'Usage Frequency', 'Purchase History',
       'Favorite Genres', 'Devices Used', 'Engagement Metrics',
       'Feedback/Ratings', 'Customer Support Interactions'], dtype=object)

# **01. Retrieve the names and email addresses of all users.**

In [8]:
Customers_name = df["Name"]

In [9]:
Customers_name

0          Ronald Murphy
1            Scott Allen
2       Jonathan Parrish
3         Megan Williams
4          Kathryn Brown
              ...
2495       Michael Lopez
2496     Matthew Woodard
2497       Morgan Barnes
2498      Gina Castaneda
2499      Mark Nicholson
Name: Name, Length: 2500, dtype: object

In [10]:
Customers_email = df["Email Address"]

In [11]:
Customers_email

0           williamholland@example.com
1                  scott22@example.org
2                 brooke16@example.org
3              elizabeth31@example.net
4       pattersonalexandra@example.org
                     ...
2495       williamsroberto@example.org
2496               lkaiser@example.com
2497          erikaholland@example.net
2498          reedcourtney@example.net
2499           martinisaac@example.net
Name: Email Address, Length: 2500, dtype: object

In [12]:
name_email = df[["Name", "Email Address"]] #combined

In [13]:
name_email

                  Name                   Email Address
0        Ronald Murphy      williamholland@example.com
1          Scott Allen             scott22@example.org
2     Jonathan Parrish            brooke16@example.org
3       Megan Williams         elizabeth31@example.net
4        Kathryn Brown  pattersonalexandra@example.org
...                ...                             ...
2495     Michael Lopez     williamsroberto@example.org
2496   Matthew Woodard             lkaiser@example.com
2497     Morgan Barnes        erikaholland@example.net
2498    Gina Castaneda        reedcourtney@example.net
2499    Mark Nicholson         martinisaac@example.net

[2500 rows x 2 columns]

# **02. Find the number of users by gender.**

In [14]:
df["Gender"].value_counts() #1260 users are male and 1240 users are female

Gender
Male      1260
Female    1240
Name: count, dtype: int64

# **03. Get the usernames and membership start dates of users who joined before a certain date (2024-03-13).**

In [15]:
df.head(10)

,User ID,Name,Email Address,Username,Date of Birth,Gender,Location,Membership Start Date,Membership End Date,Subscription Plan,Payment Information,Renewal Status,Usage Frequency,Purchase History,Favorite Genres,Devices Used,Engagement Metrics,Feedback/Ratings,Customer Support Interactions
0,1,Ronald Murphy,williamholland@example.com,williamholland,1953-06-03,Male,Rebeccachester,2024-01-15,2025-01-14,Annual,Mastercard,Manual,Regular,Electronics,Documentary,Smart TV,Medium,3.6,3
1,2,Scott Allen,scott22@example.org,scott22,1978-07-08,Male,Mcphersonview,2024-01-07,2025-01-06,Monthly,Visa,Manual,Regular,Electronics,Horror,Smartphone,Medium,3.8,7
2,3,Jonathan Parrish,brooke16@example.org,brooke16,1994-12-06,Female,Youngfort,2024-04-13,2025-04-13,Monthly,Mastercard,Manual,Regular,Books,Comedy,Smart TV,Low,3.3,8
3,4,Megan Williams,elizabeth31@example.net,elizabeth31,1964-12-22,Female,Feliciashire,2024-01-24,2025-01-23,Monthly,Amex,Auto-renew,Regular,Electronics,Documentary,Smart TV,High,3.3,7
4,5,Kathryn Brown,pattersonalexandra@example.org,pattersonalexandra,1961-06-04,Male,Port Deborah,2024-02-14,2025-02-13,Annual,Visa,Auto-renew,Frequent,Clothing,Drama,Smart TV,Low,4.3,1
5,6,Sandra Cox,gparks@example.org,gparks,1954-09-19,Female,Lake Johnathan,2024-01-15,2025-01-14,Monthly,Amex,Manual,Occasional,Books,Action,Tablet,Low,3.8,2
6,7,Benjamin Marshall,michaellewis@example.net,michaellewis,2003-02-09,Male,Carlsonchester,2024-04-08,2025-04-08,Monthly,Amex,Auto-renew,Frequent,Clothing,Sci-Fi,Tablet,Medium,4.4,10
7,8,James Smith,adrienne49@example.org,adrienne49,1946-10-04,Male,West Matthewborough,2024-02-16,2025-02-15,Monthly,Visa,Manual,Regular,Electronics,Horror,Smart TV,Medium,3.6,6
8,9,Bradley Green,brittany02@example.net,brittany02,1950-12-24,Female,Karenshire,2024-04-09,2025-04-09,Annual,Amex,Manual,Frequent,Electronics,Documentary,Smartphone,Medium,4.0,8
9,10,Kayla Hernandez,jessica53@example.net,jessica53,1963-06-16,Male,West Stephen,2024-03-10,2025-03-10,Monthly,Visa,Auto-renew,Frequent,Clothing,Drama,Tablet,High,4.9,6

In [16]:
df["Membership Start Date"] = pd.to_datetime(df["Membership Start Date"])
membership_before_start = df[df["Membership Start Date"] < "2024-03-13"]
membership_before_start[["Username","Membership Start Date"]]

                Username Membership Start Date
0         williamholland            2024-01-15
1                scott22            2024-01-07
3            elizabeth31            2024-01-24
4     pattersonalexandra            2024-02-14
5                 gparks            2024-01-15
...                  ...                   ...
2495     williamsroberto            2024-01-25
2496             lkaiser            2024-03-03
2497        erikaholland            2024-02-09
2498        reedcourtney            2024-02-18
2499         martinisaac            2024-01-28

[1708 rows x 2 columns]

# **04. Count the number of users from a specific location (let's say, locations that contains Port).**

In [17]:
location = df[df["Location"].str.contains("port")].groupby("Location")["User ID"].count().sort_values(ascending=False)

In [18]:
location

Location
Amyport            2
Barnesport         2
Davisport          2
Shannonport        2
Stevenport         2
                  ..
West Connorport    1
West Lisaport      1
West Paulaport     1
West Staceyport    1
Williamsport       1
Name: User ID, Length: 87, dtype: int64

# **05. List the subscription plans along with the count of users subscribed to each plan.**

In [19]:
df.head(10)

,User ID,Name,Email Address,Username,Date of Birth,Gender,Location,Membership Start Date,Membership End Date,Subscription Plan,Payment Information,Renewal Status,Usage Frequency,Purchase History,Favorite Genres,Devices Used,Engagement Metrics,Feedback/Ratings,Customer Support Interactions
0,1,Ronald Murphy,williamholland@example.com,williamholland,1953-06-03,Male,Rebeccachester,2024-01-15,2025-01-14,Annual,Mastercard,Manual,Regular,Electronics,Documentary,Smart TV,Medium,3.6,3
1,2,Scott Allen,scott22@example.org,scott22,1978-07-08,Male,Mcphersonview,2024-01-07,2025-01-06,Monthly,Visa,Manual,Regular,Electronics,Horror,Smartphone,Medium,3.8,7
2,3,Jonathan Parrish,brooke16@example.org,brooke16,1994-12-06,Female,Youngfort,2024-04-13,2025-04-13,Monthly,Mastercard,Manual,Regular,Books,Comedy,Smart TV,Low,3.3,8
3,4,Megan Williams,elizabeth31@example.net,elizabeth31,1964-12-22,Female,Feliciashire,2024-01-24,2025-01-23,Monthly,Amex,Auto-renew,Regular,Electronics,Documentary,Smart TV,High,3.3,7
4,5,Kathryn Brown,pattersonalexandra@example.org,pattersonalexandra,1961-06-04,Male,Port Deborah,2024-02-14,2025-02-13,Annual,Visa,Auto-renew,Frequent,Clothing,Drama,Smart TV,Low,4.3,1
5,6,Sandra Cox,gparks@example.org,gparks,1954-09-19,Female,Lake Johnathan,2024-01-15,2025-01-14,Monthly,Amex,Manual,Occasional,Books,Action,Tablet,Low,3.8,2
6,7,Benjamin Marshall,michaellewis@example.net,michaellewis,2003-02-09,Male,Carlsonchester,2024-04-08,2025-04-08,Monthly,Amex,Auto-renew,Frequent,Clothing,Sci-Fi,Tablet,Medium,4.4,10
7,8,James Smith,adrienne49@example.org,adrienne49,1946-10-04,Male,West Matthewborough,2024-02-16,2025-02-15,Monthly,Visa,Manual,Regular,Electronics,Horror,Smart TV,Medium,3.6,6
8,9,Bradley Green,brittany02@example.net,brittany02,1950-12-24,Female,Karenshire,2024-04-09,2025-04-09,Annual,Amex,Manual,Frequent,Electronics,Documentary,Smartphone,Medium,4.0,8
9,10,Kayla Hernandez,jessica53@example.net,jessica53,1963-06-16,Male,West Stephen,2024-03-10,2025-03-10,Monthly,Visa,Auto-renew,Frequent,Clothing,Drama,Tablet,High,4.9,6

In [20]:
df["Subscription Plan"].value_counts() #here 1271 customers take annual plan and 1229 customers take monthly plan

Subscription Plan
Annual     1271
Monthly    1229
Name: count, dtype: int64

# **06. Find the usernames and their corresponding payment information.**

In [21]:
user_payment = df[["Username", "Payment Information"]].sort_values(by="Username").reset_index(drop=True)

In [22]:
user_payment

         Username Payment Information
0       aanderson          Mastercard
1         aaron27                Visa
2         aaron29          Mastercard
3         aaron39                Visa
4         aaron70          Mastercard
...           ...                 ...
2495      zwalker          Mastercard
2496  zwashington                Amex
2497    zwilliams                Amex
2498      zwilson                Visa
2499      zwilson                Amex

[2500 rows x 2 columns]

# **07. Identify the renewal status of each user's subscription.**

In [23]:
renewal_status = df[["Username", "Renewal Status"]].sort_values(by="Renewal Status").reset_index(drop=True)

In [24]:
renewal_status

             Username Renewal Status
0         martinisaac     Auto-renew
1          powersmary     Auto-renew
2     jenniferroberts     Auto-renew
3      russellantonio     Auto-renew
4           jonbrooks     Auto-renew
...               ...            ...
2495          ejensen         Manual
2496       jodihanson         Manual
2497            prose         Manual
2498       wilcoxkara         Manual
2499   jasonrasmussen         Manual

[2500 rows x 2 columns]

# **08. Calculate the average usage frequency of all users.**

In [25]:
df.head(10)

,User ID,Name,Email Address,Username,Date of Birth,Gender,Location,Membership Start Date,Membership End Date,Subscription Plan,Payment Information,Renewal Status,Usage Frequency,Purchase History,Favorite Genres,Devices Used,Engagement Metrics,Feedback/Ratings,Customer Support Interactions
0,1,Ronald Murphy,williamholland@example.com,williamholland,1953-06-03,Male,Rebeccachester,2024-01-15,2025-01-14,Annual,Mastercard,Manual,Regular,Electronics,Documentary,Smart TV,Medium,3.6,3
1,2,Scott Allen,scott22@example.org,scott22,1978-07-08,Male,Mcphersonview,2024-01-07,2025-01-06,Monthly,Visa,Manual,Regular,Electronics,Horror,Smartphone,Medium,3.8,7
2,3,Jonathan Parrish,brooke16@example.org,brooke16,1994-12-06,Female,Youngfort,2024-04-13,2025-04-13,Monthly,Mastercard,Manual,Regular,Books,Comedy,Smart TV,Low,3.3,8
3,4,Megan Williams,elizabeth31@example.net,elizabeth31,1964-12-22,Female,Feliciashire,2024-01-24,2025-01-23,Monthly,Amex,Auto-renew,Regular,Electronics,Documentary,Smart TV,High,3.3,7
4,5,Kathryn Brown,pattersonalexandra@example.org,pattersonalexandra,1961-06-04,Male,Port Deborah,2024-02-14,2025-02-13,Annual,Visa,Auto-renew,Frequent,Clothing,Drama,Smart TV,Low,4.3,1
5,6,Sandra Cox,gparks@example.org,gparks,1954-09-19,Female,Lake Johnathan,2024-01-15,2025-01-14,Monthly,Amex,Manual,Occasional,Books,Action,Tablet,Low,3.8,2
6,7,Benjamin Marshall,michaellewis@example.net,michaellewis,2003-02-09,Male,Carlsonchester,2024-04-08,2025-04-08,Monthly,Amex,Auto-renew,Frequent,Clothing,Sci-Fi,Tablet,Medium,4.4,10
7,8,James Smith,adrienne49@example.org,adrienne49,1946-10-04,Male,West Matthewborough,2024-02-16,2025-02-15,Monthly,Visa,Manual,Regular,Electronics,Horror,Smart TV,Medium,3.6,6
8,9,Bradley Green,brittany02@example.net,brittany02,1950-12-24,Female,Karenshire,2024-04-09,2025-04-09,Annual,Amex,Manual,Frequent,Electronics,Documentary,Smartphone,Medium,4.0,8
9,10,Kayla Hernandez,jessica53@example.net,jessica53,1963-06-16,Male,West Stephen,2024-03-10,2025-03-10,Monthly,Visa,Auto-renew,Frequent,Clothing,Drama,Tablet,High,4.9,6

In [26]:
df[["Name","Usage Frequency"]]

                  Name Usage Frequency
0        Ronald Murphy         Regular
1          Scott Allen         Regular
2     Jonathan Parrish         Regular
3       Megan Williams         Regular
4        Kathryn Brown        Frequent
...                ...             ...
2495     Michael Lopez        Frequent
2496   Matthew Woodard        Frequent
2497     Morgan Barnes        Frequent
2498    Gina Castaneda         Regular
2499    Mark Nicholson         Regular

[2500 rows x 2 columns]

In [27]:
df["Usage Frequency"].value_counts()

Usage Frequency
Frequent      851
Regular       827
Occasional    822
Name: count, dtype: int64

In [28]:
maped_usage = {"Frequent" : 3, "Occasional" : 1, "Regular" : 2}
df["usage"] = df["Usage Frequency"].map(maped_usage)
average_usage = float(round(df["usage"].mean(), 2))
average_usage

2.01

In [29]:
df.head()

,User ID,Name,Email Address,Username,Date of Birth,Gender,Location,Membership Start Date,Membership End Date,Subscription Plan,Payment Information,Renewal Status,Usage Frequency,Purchase History,Favorite Genres,Devices Used,Engagement Metrics,Feedback/Ratings,Customer Support Interactions,usage
0,1,Ronald Murphy,williamholland@example.com,williamholland,1953-06-03,Male,Rebeccachester,2024-01-15,2025-01-14,Annual,Mastercard,Manual,Regular,Electronics,Documentary,Smart TV,Medium,3.6,3,2
1,2,Scott Allen,scott22@example.org,scott22,1978-07-08,Male,Mcphersonview,2024-01-07,2025-01-06,Monthly,Visa,Manual,Regular,Electronics,Horror,Smartphone,Medium,3.8,7,2
2,3,Jonathan Parrish,brooke16@example.org,brooke16,1994-12-06,Female,Youngfort,2024-04-13,2025-04-13,Monthly,Mastercard,Manual,Regular,Books,Comedy,Smart TV,Low,3.3,8,2
3,4,Megan Williams,elizabeth31@example.net,elizabeth31,1964-12-22,Female,Feliciashire,2024-01-24,2025-01-23,Monthly,Amex,Auto-renew,Regular,Electronics,Documentary,Smart TV,High,3.3,7,2
4,5,Kathryn Brown,pattersonalexandra@example.org,pattersonalexandra,1961-06-04,Male,Port Deborah,2024-02-14,2025-02-13,Annual,Visa,Auto-renew,Frequent,Clothing,Drama,Smart TV,Low,4.3,1,3

# **09. Determine the number of users with a specific purchase history.**

In [30]:
df["Purchase History"].value_counts()

Purchase History
Books          851
Electronics    847
Clothing       802
Name: count, dtype: int64

# **10. List the favorite genres of users along with the count of users for each genre.**

In [31]:
df["Favorite Genres"].value_counts() #favourite genres are horror and action

Favorite Genres
Horror         383
Action         380
Romance        368
Drama          361
Comedy         349
Documentary    340
Sci-Fi         319
Name: count, dtype: int64

# **11. Calculate the Average feedback or ratings given by users.**

In [32]:
df.head(10)

,User ID,Name,Email Address,Username,Date of Birth,Gender,Location,Membership Start Date,Membership End Date,Subscription Plan,Payment Information,Renewal Status,Usage Frequency,Purchase History,Favorite Genres,Devices Used,Engagement Metrics,Feedback/Ratings,Customer Support Interactions,usage
0,1,Ronald Murphy,williamholland@example.com,williamholland,1953-06-03,Male,Rebeccachester,2024-01-15,2025-01-14,Annual,Mastercard,Manual,Regular,Electronics,Documentary,Smart TV,Medium,3.6,3,2
1,2,Scott Allen,scott22@example.org,scott22,1978-07-08,Male,Mcphersonview,2024-01-07,2025-01-06,Monthly,Visa,Manual,Regular,Electronics,Horror,Smartphone,Medium,3.8,7,2
2,3,Jonathan Parrish,brooke16@example.org,brooke16,1994-12-06,Female,Youngfort,2024-04-13,2025-04-13,Monthly,Mastercard,Manual,Regular,Books,Comedy,Smart TV,Low,3.3,8,2
3,4,Megan Williams,elizabeth31@example.net,elizabeth31,1964-12-22,Female,Feliciashire,2024-01-24,2025-01-23,Monthly,Amex,Auto-renew,Regular,Electronics,Documentary,Smart TV,High,3.3,7,2
4,5,Kathryn Brown,pattersonalexandra@example.org,pattersonalexandra,1961-06-04,Male,Port Deborah,2024-02-14,2025-02-13,Annual,Visa,Auto-renew,Frequent,Clothing,Drama,Smart TV,Low,4.3,1,3
5,6,Sandra Cox,gparks@example.org,gparks,1954-09-19,Female,Lake Johnathan,2024-01-15,2025-01-14,Monthly,Amex,Manual,Occasional,Books,Action,Tablet,Low,3.8,2,1
6,7,Benjamin Marshall,michaellewis@example.net,michaellewis,2003-02-09,Male,Carlsonchester,2024-04-08,2025-04-08,Monthly,Amex,Auto-renew,Frequent,Clothing,Sci-Fi,Tablet,Medium,4.4,10,3
7,8,James Smith,adrienne49@example.org,adrienne49,1946-10-04,Male,West Matthewborough,2024-02-16,2025-02-15,Monthly,Visa,Manual,Regular,Electronics,Horror,Smart TV,Medium,3.6,6,2
8,9,Bradley Green,brittany02@example.net,brittany02,1950-12-24,Female,Karenshire,2024-04-09,2025-04-09,Annual,Amex,Manual,Frequent,Electronics,Documentary,Smartphone,Medium,4.0,8,3
9,10,Kayla Hernandez,jessica53@example.net,jessica53,1963-06-16,Male,West Stephen,2024-03-10,2025-03-10,Monthly,Visa,Auto-renew,Frequent,Clothing,Drama,Tablet,High,4.9,6,3

In [33]:
df.groupby('Purchase History')['Feedback/Ratings'].mean()

Purchase History
Books          3.997885
Clothing       3.978678
Electronics    4.036364
Name: Feedback/Ratings, dtype: float64

# **12. Get the usernames of users who have renewed their subscription.**

In [34]:
df["Renewal Status"].value_counts()

Renewal Status
Auto-renew    1274
Manual        1226
Name: count, dtype: int64

In [41]:
renewed_user = df[df['Renewal Status'] == 'Auto-renew'].reset_index(drop=True)
renewed_user['Username']

0              elizabeth31
1       pattersonalexandra
2             michaellewis
3                jessica53
4                   hochoa
               ...
1269                jirwin
1270            virginia02
1271     andersonchristina
1272       williamsroberto
1273           martinisaac
Name: Username, Length: 1274, dtype: object

# **13. Find the usernames of users who have not made any purchases.**

In [42]:
df.head(5)

,User ID,Name,Email Address,Username,Date of Birth,Gender,Location,Membership Start Date,Membership End Date,Subscription Plan,Payment Information,Renewal Status,Usage Frequency,Purchase History,Favorite Genres,Devices Used,Engagement Metrics,Feedback/Ratings,Customer Support Interactions,usage
0,1,Ronald Murphy,williamholland@example.com,williamholland,1953-06-03,Male,Rebeccachester,2024-01-15,2025-01-14,Annual,Mastercard,Manual,Regular,Electronics,Documentary,Smart TV,Medium,3.6,3,2
1,2,Scott Allen,scott22@example.org,scott22,1978-07-08,Male,Mcphersonview,2024-01-07,2025-01-06,Monthly,Visa,Manual,Regular,Electronics,Horror,Smartphone,Medium,3.8,7,2
2,3,Jonathan Parrish,brooke16@example.org,brooke16,1994-12-06,Female,Youngfort,2024-04-13,2025-04-13,Monthly,Mastercard,Manual,Regular,Books,Comedy,Smart TV,Low,3.3,8,2
3,4,Megan Williams,elizabeth31@example.net,elizabeth31,1964-12-22,Female,Feliciashire,2024-01-24,2025-01-23,Monthly,Amex,Auto-renew,Regular,Electronics,Documentary,Smart TV,High,3.3,7,2
4,5,Kathryn Brown,pattersonalexandra@example.org,pattersonalexandra,1961-06-04,Male,Port Deborah,2024-02-14,2025-02-13,Annual,Visa,Auto-renew,Frequent,Clothing,Drama,Smart TV,Low,4.3,1,3

In [47]:
df['Purchase History'].isnull().sum() #so ther doesnot exist any username who have not made any purchases.

np.int64(0)

# **14. Identify the most frequently used device among users.**

In [54]:
most_frequent_device = df["Devices Used"].value_counts().idxmax()
print(f"The most frequently used device is: {most_frequent_device}")

The most frequently used device is: Smartphone

# **15. List the usernames and their corresponding locations for users who are highly engaged.**

In [60]:
highly_engaged = df[df["Engagement Metrics"] == 'High']
highly_engaged[["Username","Location"]].reset_index(drop=True)

           Username           Location
0       elizabeth31       Feliciashire
1         jessica53       West Stephen
2         phumphrey        New Brandon
3          ronald82       North Audrey
4     castillokatie       West Raymond
..              ...                ...
840  guzmanmichelle         Garzaburgh
841          jirwin    Port Cheryltown
842      virginia02  North Tinaborough
843    reedcourtney       Williammouth
844     martinisaac     Estradaborough

[845 rows x 2 columns]